version: "3.9"

services:
  backend:
    build: .
    container_name: backend_flask
    ports:
      - "3000:3000"
    volumes:
      - /home/minipc/backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: always
