version: "3.9"

services:
  backend:
    build: .
    container_name: backend_flask
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - /home/minipc/backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: always
    # LIMITES DE RECURSOS (FORMA CORRECTA)
    cpus: 3.5  # Límite de CPUs
    mem_limit: 900m  # Límite de memoria
